version: "3"
services:
    nginx:
        image: nginx:1.17.9-alpine
        container_name: nginx
        volumes:
          - "./nginx/conf.d:/etc/nginx/conf.d"
          - "./www:/var/www"
        ports:
          - "80:80"
        networks:
           - default
    apache:
        build:
            context: ./
            dockerfile: apache2-php
        container_name: apache2-php-pyhon
        ports:
            - "8080:80"
        volumes:
            - "./www:/var/www/"
        networks:
            - default   
    
